name: Update

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron:  '0 12 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install pygithub
      - run: python sync.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
